package com.sneakerate.web.populator.feed;

import com.sneakerate.web.domain.Sneaker;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

@Service
public class ImagePopulator {
    private static final Logger LOGGER = LoggerFactory.getLogger(ImagePopulator.class);

    public void populate(Map<String, Sneaker> urlToSneaker) {
        LOGGER.info("Started populating image data...");

        Sneaker sneaker = urlToSneaker.get("puma-ignite-evoknit");
        List<List<String>> images = sneaker.getImages();
        List<String> group1 = new ArrayList<>();
        group1.add("puma-ignite-evoknit-red-white-1");
        group1.add("puma-ignite-evoknit-red-white-2");
        group1.add("puma-ignite-evoknit-red-white-3");
        group1.add("puma-ignite-evoknit-red-white-4");
        group1.add("puma-ignite-evoknit-red-white-5");
        group1.add("puma-ignite-evoknit-red-white-6");
        group1.add("puma-ignite-evoknit-red-white-7");
        group1.add("puma-ignite-evoknit-red-white-8");
        List<String> group2 = new ArrayList<>();
        group2.add("puma-ignite-evoknit-black-white-1");
        group2.add("puma-ignite-evoknit-black-white-2");
        group2.add("puma-ignite-evoknit-black-white-3");
        group2.add("puma-ignite-evoknit-black-white-4");
        group2.add("puma-ignite-evoknit-black-white-5");
        group2.add("puma-ignite-evoknit-black-white-6");
        group2.add("puma-ignite-evoknit-black-white-7");
        group2.add("puma-ignite-evoknit-black-white-8");
        List<String> group3 = new ArrayList<>();
        group3.add("puma-ignite-evoknit-olive-1");
        group3.add("puma-ignite-evoknit-olive-2");
        group3.add("puma-ignite-evoknit-olive-3");
        group3.add("puma-ignite-evoknit-olive-4");
        group3.add("puma-ignite-evoknit-olive-5");
        group3.add("puma-ignite-evoknit-olive-6");
        group3.add("puma-ignite-evoknit-olive-7");
        group3.add("puma-ignite-evoknit-olive-8");
        List<String> group5 = new ArrayList<>();
        group5.add("puma-ignite-evoknit-red-1");
        group5.add("puma-ignite-evoknit-red-2");
        group5.add("puma-ignite-evoknit-red-3");
        group5.add("puma-ignite-evoknit-red-4");
        List<String> group6 = new ArrayList<>();
        group6.add("puma-ignite-evoknit-black-1");
        group6.add("puma-ignite-evoknit-black-2");
        group6.add("puma-ignite-evoknit-black-3");
        group6.add("puma-ignite-evoknit-black-4");
        images.add(group1);
        images.add(group2);
        images.add(group3);
        images.add(group5);
        images.add(group6);
        List<String> amazonLinks = sneaker.getAmazonLinks();
        amazonLinks.add("https://www.amazon.com/gp/product/B01J5F34I0/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&tag=sneakeracom-20&camp=1789&creative=9325&linkCode=as2&creativeASIN=B01J5F34I0&linkId=d17ace53c1cecd3cd01ba6bd71b9be89");
        amazonLinks.add("https://www.amazon.com/gp/product/B01J5F34I0/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&tag=sneakeracom-20&camp=1789&creative=9325&linkCode=as2&creativeASIN=B01J5F34I0&linkId=d17ace53c1cecd3cd01ba6bd71b9be89");
        amazonLinks.add("https://www.amazon.com/gp/product/B01J5F34I0/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&tag=sneakeracom-20&camp=1789&creative=9325&linkCode=as2&creativeASIN=B01J5F34I0&linkId=d17ace53c1cecd3cd01ba6bd71b9be89");
        amazonLinks.add("https://www.amazon.com/gp/product/B01J5F34I0/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&tag=sneakeracom-20&camp=1789&creative=9325&linkCode=as2&creativeASIN=B01J5F34I0&linkId=d17ace53c1cecd3cd01ba6bd71b9be89");
        amazonLinks.add("https://www.amazon.com/gp/product/B01J5F34I0/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&tag=sneakeracom-20&camp=1789&creative=9325&linkCode=as2&creativeASIN=B01J5F34I0&linkId=d17ace53c1cecd3cd01ba6bd71b9be89");

        sneaker = urlToSneaker.get("puma-kylie-jenner");
        images = sneaker.getImages();
        group1 = new ArrayList<>();
        group1.add("puma-kylie-jenner-black-1");
        group1.add("puma-kylie-jenner-black-2");
        group1.add("puma-kylie-jenner-black-3");
        group1.add("puma-kylie-jenner-black-4");
        group1.add("puma-kylie-jenner-black-5");
        group1.add("puma-kylie-jenner-black-6");
        group1.add("puma-kylie-jenner-black-7");
        group1.add("puma-kylie-jenner-black-8");
        group2 = new ArrayList<>();
        group2.add("puma-kylie-jenner-red-1");
        group2.add("puma-kylie-jenner-red-2");
        group2.add("puma-kylie-jenner-red-3");
        group2.add("puma-kylie-jenner-red-4");
        group2.add("puma-kylie-jenner-red-5");
        group2.add("puma-kylie-jenner-red-6");
        group2.add("puma-kylie-jenner-red-7");
        group2.add("puma-kylie-jenner-red-8");
        group3 = new ArrayList<>();
        group3.add("puma-kylie-jenner-grey-1");
        group3.add("puma-kylie-jenner-grey-2");
        group3.add("puma-kylie-jenner-grey-3");
        group3.add("puma-kylie-jenner-grey-4");
        group3.add("puma-kylie-jenner-grey-5");
        group3.add("puma-kylie-jenner-grey-6");
        group3.add("puma-kylie-jenner-grey-7");
        List<String> group4 = new ArrayList<>();
        group4.add("puma-kylie-jenner-grey-black-1");
        group4.add("puma-kylie-jenner-grey-black-2");
        group4.add("puma-kylie-jenner-grey-black-3");
        group4.add("puma-kylie-jenner-grey-black-4");
        group4.add("puma-kylie-jenner-grey-black-5");
        group4.add("puma-kylie-jenner-grey-black-6");
        group4.add("puma-kylie-jenner-grey-black-7");
        images.add(group4);
        images.add(group1);
        images.add(group2);
        images.add(group3);
        amazonLinks = sneaker.getAmazonLinks();
        amazonLinks.add("https://www.amazon.com/gp/product/B01BOUG120/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&tag=sneakeracom-20&camp=1789&creative=9325&linkCode=as2&creativeASIN=B01BOUG120&linkId=b7bc7e645d857e854ebb04ae02cd378f");
        amazonLinks.add("https://www.amazon.com/gp/product/B01BOUG120/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&tag=sneakeracom-20&camp=1789&creative=9325&linkCode=as2&creativeASIN=B01BOUG120&linkId=b7bc7e645d857e854ebb04ae02cd378f");
        amazonLinks.add("https://www.amazon.com/gp/product/B01BOUG120/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&tag=sneakeracom-20&camp=1789&creative=9325&linkCode=as2&creativeASIN=B01BOUG120&linkId=b7bc7e645d857e854ebb04ae02cd378f");
        amazonLinks.add("https://www.amazon.com/gp/product/B01BOUG120/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&tag=sneakeracom-20&camp=1789&creative=9325&linkCode=as2&creativeASIN=B01BOUG120&linkId=b7bc7e645d857e854ebb04ae02cd378f");

        sneaker = urlToSneaker.get("adidas-cloudfoam-flyer");
        images = sneaker.getImages();
        group1 = new ArrayList<>();
        group1.add("adidas-cloudfoam-flyer-unity-ink-white-sun-glow-1");
        group1.add("adidas-cloudfoam-flyer-unity-ink-white-sun-glow-2");
        group1.add("adidas-cloudfoam-flyer-unity-ink-white-sun-glow-3");
        group1.add("adidas-cloudfoam-flyer-unity-ink-white-sun-glow-4");
        group1.add("adidas-cloudfoam-flyer-unity-ink-white-sun-glow-5");
        group1.add("adidas-cloudfoam-flyer-unity-ink-white-sun-glow-6");
        group1.add("adidas-cloudfoam-flyer-unity-ink-white-sun-glow-7");
        group2 = new ArrayList<>();
        group2.add("adidas-cloudfoam-flyer-black-shock-pink-1");
        group2.add("adidas-cloudfoam-flyer-black-shock-pink-2");
        group2.add("adidas-cloudfoam-flyer-black-shock-pink-3");
        group2.add("adidas-cloudfoam-flyer-black-shock-pink-4");
        group2.add("adidas-cloudfoam-flyer-black-shock-pink-5");
        group2.add("adidas-cloudfoam-flyer-black-shock-pink-6");
        group3 = new ArrayList<>();
        group3.add("adidas-cloudfoam-flyer-grey-white-blue-1");
        group3.add("adidas-cloudfoam-flyer-grey-white-blue-2");
        group3.add("adidas-cloudfoam-flyer-grey-white-blue-3");
        group3.add("adidas-cloudfoam-flyer-grey-white-blue-4");
        group3.add("adidas-cloudfoam-flyer-grey-white-blue-5");
        group3.add("adidas-cloudfoam-flyer-grey-white-blue-6");
        group3.add("adidas-cloudfoam-flyer-grey-white-blue-7");
        group4 = new ArrayList<>();
        group4.add("adidas-cloudfoam-flyer-grey-silver-black-1");
        group4.add("adidas-cloudfoam-flyer-grey-silver-black-2");
        group4.add("adidas-cloudfoam-flyer-grey-silver-black-3");
        group4.add("adidas-cloudfoam-flyer-grey-silver-black-4");
        group4.add("adidas-cloudfoam-flyer-grey-silver-black-5");
        group4.add("adidas-cloudfoam-flyer-grey-silver-black-6");
        group4.add("adidas-cloudfoam-flyer-grey-silver-black-7");
        group5 = new ArrayList<>();
        group5.add("adidas-cloudfoam-flyer-infrared-black-silver-1");
        group5.add("adidas-cloudfoam-flyer-infrared-black-silver-2");
        group5.add("adidas-cloudfoam-flyer-infrared-black-silver-3");
        group5.add("adidas-cloudfoam-flyer-infrared-black-silver-4");
        group5.add("adidas-cloudfoam-flyer-infrared-black-silver-5");
        group5.add("adidas-cloudfoam-flyer-infrared-black-silver-6");
        group5.add("adidas-cloudfoam-flyer-infrared-black-silver-7");
        group6 = new ArrayList<>();
        group6.add("adidas-cloudfoam-flyer-ink-navy-satellite-1");
        group6.add("adidas-cloudfoam-flyer-ink-navy-satellite-2");
        group6.add("adidas-cloudfoam-flyer-ink-navy-satellite-3");
        group6.add("adidas-cloudfoam-flyer-ink-navy-satellite-4");
        group6.add("adidas-cloudfoam-flyer-ink-navy-satellite-5");
        group6.add("adidas-cloudfoam-flyer-ink-navy-satellite-6");
        group6.add("adidas-cloudfoam-flyer-ink-navy-satellite-7");
        group6.add("adidas-cloudfoam-flyer-ink-navy-satellite-8");
        List<String> group7 = new ArrayList<>();
        group7.add("adidas-cloudfoam-flyer-onix-black-silver-1");
        group7.add("adidas-cloudfoam-flyer-onix-black-silver-2");
        group7.add("adidas-cloudfoam-flyer-onix-black-silver-3");
        group7.add("adidas-cloudfoam-flyer-onix-black-silver-4");
        group7.add("adidas-cloudfoam-flyer-onix-black-silver-5");
        group7.add("adidas-cloudfoam-flyer-onix-black-silver-6");
        group7.add("adidas-cloudfoam-flyer-onix-black-silver-7");
        group7.add("adidas-cloudfoam-flyer-onix-black-silver-8");
        images.add(group5);
        images.add(group1);
        images.add(group2);
        images.add(group3);
        images.add(group4);
        images.add(group6);
        images.add(group7);
        amazonLinks = sneaker.getAmazonLinks();
        amazonLinks.add("https://www.amazon.com/gp/product/B01A1DUFTG/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&tag=sneakeracom-20&camp=1789&creative=9325&linkCode=as2&creativeASIN=B01A1DUFTG&linkId=30216ed66d1c3ff9f930b86ee91b0364");
        amazonLinks.add("https://www.amazon.com/gp/product/B01A1FG2Y6/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&tag=sneakeracom-20&camp=1789&creative=9325&linkCode=as2&creativeASIN=B01A1FG2Y6&linkId=25bf64b937abc2206be335b33a8eb490");
        amazonLinks.add("https://www.amazon.com/gp/product/B01A1FG2Y6/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&tag=sneakeracom-20&camp=1789&creative=9325&linkCode=as2&creativeASIN=B01A1FG2Y6&linkId=25bf64b937abc2206be335b33a8eb490");
        amazonLinks.add("https://www.amazon.com/gp/product/B01A1DUFTG/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&tag=sneakeracom-20&camp=1789&creative=9325&linkCode=as2&creativeASIN=B01A1DUFTG&linkId=30216ed66d1c3ff9f930b86ee91b0364");
        amazonLinks.add("https://www.amazon.com/gp/product/B01A1DUFTG/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&tag=sneakeracom-20&camp=1789&creative=9325&linkCode=as2&creativeASIN=B01A1DUFTG&linkId=30216ed66d1c3ff9f930b86ee91b0364");
        amazonLinks.add("https://www.amazon.com/gp/product/B01A1DUFTG/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&tag=sneakeracom-20&camp=1789&creative=9325&linkCode=as2&creativeASIN=B01A1DUFTG&linkId=30216ed66d1c3ff9f930b86ee91b0364");
        amazonLinks.add("https://www.amazon.com/gp/product/B01A1DUFTG/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&tag=sneakeracom-20&camp=1789&creative=9325&linkCode=as2&creativeASIN=B01A1DUFTG&linkId=30216ed66d1c3ff9f930b86ee91b0364");

        sneaker = urlToSneaker.get("adidas-superstar");
        images = sneaker.getImages();
        group1 = new ArrayList<>();
        group1.add("adidas-superstar-white-black-gold-1");
        group1.add("adidas-superstar-white-black-gold-2");
        group1.add("adidas-superstar-white-black-gold-3");
        group1.add("adidas-superstar-white-black-gold-4");
        group1.add("adidas-superstar-white-black-gold-5");
        group1.add("adidas-superstar-white-black-gold-6");
        group1.add("adidas-superstar-white-black-gold-7");
        group1.add("adidas-superstar-white-black-gold-8");
        group2 = new ArrayList<>();
        group2.add("adidas-superstar-white-red-gold-1");
        group2.add("adidas-superstar-white-red-gold-2");
        group2.add("adidas-superstar-white-red-gold-3");
        group2.add("adidas-superstar-white-red-gold-4");
        group2.add("adidas-superstar-white-red-gold-5");
        group2.add("adidas-superstar-white-red-gold-6");
        group2.add("adidas-superstar-white-red-gold-7");
        group2.add("adidas-superstar-white-red-gold-8");
        group3 = new ArrayList<>();
        group3.add("adidas-superstar-white-blue-gold-1");
        group3.add("adidas-superstar-white-blue-gold-2");
        group3.add("adidas-superstar-white-blue-gold-3");
        group3.add("adidas-superstar-white-blue-gold-4");
        group3.add("adidas-superstar-white-blue-gold-5");
        group3.add("adidas-superstar-white-blue-gold-6");
        group3.add("adidas-superstar-white-blue-gold-7");
        group3.add("adidas-superstar-white-blue-gold-8");
        group4 = new ArrayList<>();
        group4.add("adidas-superstar-black-1");
        group4.add("adidas-superstar-black-2");
        group4.add("adidas-superstar-black-3");
        group4.add("adidas-superstar-black-4");
        group4.add("adidas-superstar-black-5");
        group4.add("adidas-superstar-black-6");
        group4.add("adidas-superstar-black-7");
        group5 = new ArrayList<>();
        group5.add("adidas-superstar-black-white-1");
        group5.add("adidas-superstar-black-white-2");
        group5.add("adidas-superstar-black-white-3");
        group5.add("adidas-superstar-black-white-4");
        group5.add("adidas-superstar-black-white-5");
        group5.add("adidas-superstar-black-white-6");
        group5.add("adidas-superstar-black-white-7");
        group5.add("adidas-superstar-black-white-8");
        group6 = new ArrayList<>();
        group6.add("adidas-superstar-white-1");
        group6.add("adidas-superstar-white-2");
        group6.add("adidas-superstar-white-3");
        group6.add("adidas-superstar-white-4");
        group6.add("adidas-superstar-white-5");
        group6.add("adidas-superstar-white-6");
        group6.add("adidas-superstar-white-7");
        group6.add("adidas-superstar-white-8");
        images.add(group1);
        images.add(group2);
        images.add(group3);
        images.add(group4);
        images.add(group5);
        images.add(group6);
        amazonLinks = sneaker.getAmazonLinks();
        amazonLinks.add("https://www.amazon.com/gp/product/B00LFSF9ES/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&tag=sneakeracom-20&camp=1789&creative=9325&linkCode=as2&creativeASIN=B00LFSF9ES&linkId=fc99a4740b053d5bbefcd763e864a1fa");
        amazonLinks.add("https://www.amazon.com/gp/product/B00LFSF9ES/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&tag=sneakeracom-20&camp=1789&creative=9325&linkCode=as2&creativeASIN=B00LFSF9ES&linkId=fc99a4740b053d5bbefcd763e864a1fa");
        amazonLinks.add("https://www.amazon.com/gp/product/B00LFSF9ES/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&tag=sneakeracom-20&camp=1789&creative=9325&linkCode=as2&creativeASIN=B00LFSF9ES&linkId=fc99a4740b053d5bbefcd763e864a1fa");
        amazonLinks.add("https://www.amazon.com/gp/product/B00LFSF9ES/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&tag=sneakeracom-20&camp=1789&creative=9325&linkCode=as2&creativeASIN=B00LFSF9ES&linkId=fc99a4740b053d5bbefcd763e864a1fa");
        amazonLinks.add("https://www.amazon.com/gp/product/B00LFSF9ES/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&tag=sneakeracom-20&camp=1789&creative=9325&linkCode=as2&creativeASIN=B00LFSF9ES&linkId=fc99a4740b053d5bbefcd763e864a1fa");
        amazonLinks.add("https://www.amazon.com/gp/product/B00LFSF9ES/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&tag=sneakeracom-20&camp=1789&creative=9325&linkCode=as2&creativeASIN=B00LFSF9ES&linkId=fc99a4740b053d5bbefcd763e864a1fa");

        sneaker = urlToSneaker.get("nike-air-force-1");
        images = sneaker.getImages();
        group1 = new ArrayList<>();
        group1.add("nike-air-force-1-high-black-1");
        group1.add("nike-air-force-1-high-black-2");
        group1.add("nike-air-force-1-high-black-3");
        group1.add("nike-air-force-1-high-black-4");
        group1.add("nike-air-force-1-high-black-5");
        group1.add("nike-air-force-1-high-black-6");
        group1.add("nike-air-force-1-high-black-7");
        group2 = new ArrayList<>();
        group2.add("nike-air-force-1-high-white-1");
        group2.add("nike-air-force-1-high-white-2");
        group2.add("nike-air-force-1-high-white-3");
        group2.add("nike-air-force-1-high-white-4");
        group2.add("nike-air-force-1-high-white-5");
        group2.add("nike-air-force-1-high-white-6");
        group2.add("nike-air-force-1-high-white-7");
        group3 = new ArrayList<>();
        group3.add("nike-air-force-1-black-1");
        group3.add("nike-air-force-1-black-2");
        group3.add("nike-air-force-1-black-3");
        group3.add("nike-air-force-1-black-4");
        group3.add("nike-air-force-1-black-5");
        group3.add("nike-air-force-1-black-6");
        group3.add("nike-air-force-1-black-7");
        group4 = new ArrayList<>();
        group4.add("nike-air-force-1-white-1");
        group4.add("nike-air-force-1-white-2");
        group4.add("nike-air-force-1-white-3");
        group4.add("nike-air-force-1-white-4");
        group4.add("nike-air-force-1-white-5");
        group4.add("nike-air-force-1-white-6");
        group4.add("nike-air-force-1-white-7");
        images.add(group1);
        images.add(group2);
        images.add(group3);
        images.add(group4);
        amazonLinks = sneaker.getAmazonLinks();
        amazonLinks.add("https://www.amazon.com/gp/product/B00KMJRT2Q/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&tag=sneakeracom-20&camp=1789&creative=9325&linkCode=as2&creativeASIN=B00KMJRT2Q&linkId=86f3b291c0e1e97c87d8e9d6baf27fdc");
        amazonLinks.add("https://www.amazon.com/gp/product/B00KMJRT2Q/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&tag=sneakeracom-20&camp=1789&creative=9325&linkCode=as2&creativeASIN=B00KMJRT2Q&linkId=86f3b291c0e1e97c87d8e9d6baf27fdc");
        amazonLinks.add("https://www.amazon.com/gp/product/B0064BCF84/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&tag=sneakeracom-20&camp=1789&creative=9325&linkCode=as2&creativeASIN=B0064BCF84&linkId=eaa83e409269965b49239ef0998c9636");
        amazonLinks.add("https://www.amazon.com/gp/product/B0064BCF84/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&tag=sneakeracom-20&camp=1789&creative=9325&linkCode=as2&creativeASIN=B0064BCF84&linkId=eaa83e409269965b49239ef0998c9636");

        sneaker = urlToSneaker.get("nike-air-max-90");
        images = sneaker.getImages();
        group1 = new ArrayList<>();
        group1.add("nike-air-max-90-white-1");
        group1.add("nike-air-max-90-white-2");
        group1.add("nike-air-max-90-white-3");
        group1.add("nike-air-max-90-white-4");
        group1.add("nike-air-max-90-white-5");
        group1.add("nike-air-max-90-white-6");
        group1.add("nike-air-max-90-white-7");
        group1.add("nike-air-max-90-white-8");
        group2 = new ArrayList<>();
        group2.add("nike-air-max-90-black-1");
        group2.add("nike-air-max-90-black-2");
        group2.add("nike-air-max-90-black-3");
        group2.add("nike-air-max-90-black-4");
        group2.add("nike-air-max-90-black-5");
        group2.add("nike-air-max-90-black-6");
        group2.add("nike-air-max-90-black-7");
        group2.add("nike-air-max-90-black-8");
        group3 = new ArrayList<>();
        group3.add("nike-air-max-90-orange-grey-white-1");
        group3.add("nike-air-max-90-orange-grey-white-2");
        group3.add("nike-air-max-90-orange-grey-white-3");
        group4 = new ArrayList<>();
        group4.add("nike-air-max-90-red-grey-white-1");
        group4.add("nike-air-max-90-red-grey-white-2");
        group4.add("nike-air-max-90-red-grey-white-3");
        group5 = new ArrayList<>();
        group5.add("nike-air-max-90-blue-white-black-1");
        group5.add("nike-air-max-90-blue-white-black-2");
        group5.add("nike-air-max-90-blue-white-black-3");
        images.add(group2);
        images.add(group1);
        images.add(group3);
        images.add(group4);
        images.add(group5);
        amazonLinks = sneaker.getAmazonLinks();
        amazonLinks.add("https://www.amazon.com/gp/product/B009NK0DMS/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&tag=sneakeracom-20&camp=1789&creative=9325&linkCode=as2&creativeASIN=B009NK0DMS&linkId=46023689d60e85fc7b57e0302f8375dd");
        amazonLinks.add("https://www.amazon.com/gp/product/B009NK0DMS/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&tag=sneakeracom-20&camp=1789&creative=9325&linkCode=as2&creativeASIN=B009NK0DMS&linkId=46023689d60e85fc7b57e0302f8375dd");
        amazonLinks.add("https://www.amazon.com/gp/product/B009NK0DMS/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&tag=sneakeracom-20&camp=1789&creative=9325&linkCode=as2&creativeASIN=B009NK0DMS&linkId=46023689d60e85fc7b57e0302f8375dd");
        amazonLinks.add("https://www.amazon.com/gp/product/B009NK0DMS/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&tag=sneakeracom-20&camp=1789&creative=9325&linkCode=as2&creativeASIN=B009NK0DMS&linkId=46023689d60e85fc7b57e0302f8375dd");
        amazonLinks.add("https://www.amazon.com/gp/product/B009NK0DMS/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&tag=sneakeracom-20&camp=1789&creative=9325&linkCode=as2&creativeASIN=B009NK0DMS&linkId=46023689d60e85fc7b57e0302f8375dd");

        sneaker = urlToSneaker.get("converse-chuck-taylor-all-star");
        images = sneaker.getImages();
        group1 = new ArrayList<>();
        group1.add("converse-chuck-taylor-all-star-black-white-1");
        group1.add("converse-chuck-taylor-all-star-black-white-2");
        group1.add("converse-chuck-taylor-all-star-black-white-3");
        group1.add("converse-chuck-taylor-all-star-black-white-4");
        group1.add("converse-chuck-taylor-all-star-black-white-5");
        group1.add("converse-chuck-taylor-all-star-black-white-6");
        group2 = new ArrayList<>();
        group2.add("converse-chuck-taylor-all-star-black-1");
        group2.add("converse-chuck-taylor-all-star-black-2");
        group2.add("converse-chuck-taylor-all-star-black-3");
        group2.add("converse-chuck-taylor-all-star-black-4");
        group2.add("converse-chuck-taylor-all-star-black-5");
        group2.add("converse-chuck-taylor-all-star-black-6");
        group3 = new ArrayList<>();
        group3.add("converse-chuck-taylor-all-star-white-1");
        group3.add("converse-chuck-taylor-all-star-white-2");
        group3.add("converse-chuck-taylor-all-star-white-3");
        group3.add("converse-chuck-taylor-all-star-white-4");
        group3.add("converse-chuck-taylor-all-star-white-5");
        group3.add("converse-chuck-taylor-all-star-white-6");
        group3.add("converse-chuck-taylor-all-star-white-7");
        group3.add("converse-chuck-taylor-all-star-white-8");
        group3.add("converse-chuck-taylor-all-star-white-9");
        group4 = new ArrayList<>();
        group4.add("converse-chuck-taylor-all-star-red-1");
        group4.add("converse-chuck-taylor-all-star-red-2");
        group4.add("converse-chuck-taylor-all-star-red-3");
        group4.add("converse-chuck-taylor-all-star-red-4");
        group4.add("converse-chuck-taylor-all-star-red-5");
        group4.add("converse-chuck-taylor-all-star-red-6");
        group4.add("converse-chuck-taylor-all-star-red-7");
        images.add(group1);
        images.add(group2);
        images.add(group3);
        images.add(group4);
        amazonLinks = sneaker.getAmazonLinks();
        amazonLinks.add("https://www.amazon.com/gp/product/B000LFAQDU/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&tag=sneakeracom-20&camp=1789&creative=9325&linkCode=as2&creativeASIN=B000LFAQDU&linkId=e12ed6a2d5f91868f86491a94be59b22");
        amazonLinks.add("https://www.amazon.com/gp/product/B000LFAQDU/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&tag=sneakeracom-20&camp=1789&creative=9325&linkCode=as2&creativeASIN=B000LFAQDU&linkId=e12ed6a2d5f91868f86491a94be59b22");
        amazonLinks.add("https://www.amazon.com/gp/product/B000LFAQDU/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&tag=sneakeracom-20&camp=1789&creative=9325&linkCode=as2&creativeASIN=B000LFAQDU&linkId=e12ed6a2d5f91868f86491a94be59b22");
        amazonLinks.add("https://www.amazon.com/gp/product/B000LFAQDU/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&tag=sneakeracom-20&camp=1789&creative=9325&linkCode=as2&creativeASIN=B000LFAQDU&linkId=e12ed6a2d5f91868f86491a94be59b22");

        sneaker = urlToSneaker.get("nike-air-jordan-1");
        images = sneaker.getImages();
        group1 = new ArrayList<>();
        group1.add("nike-air-jordan-1-black-red-white-1");
        group1.add("nike-air-jordan-1-black-red-white-2");
        group1.add("nike-air-jordan-1-black-red-white-3");
        group1.add("nike-air-jordan-1-black-red-white-4");
        group1.add("nike-air-jordan-1-black-red-white-5");
        group1.add("nike-air-jordan-1-black-red-white-6");
        group1.add("nike-air-jordan-1-black-red-white-7");
        group2 = new ArrayList<>();
        group2.add("nike-air-jordan-1-white-red-1");
        group2.add("nike-air-jordan-1-white-red-2");
        group2.add("nike-air-jordan-1-white-red-3");
        group2.add("nike-air-jordan-1-white-red-4");
        group2.add("nike-air-jordan-1-white-red-5");
        group2.add("nike-air-jordan-1-white-red-6");
        group2.add("nike-air-jordan-1-white-red-7");
        group3 = new ArrayList<>();
        group3.add("nike-air-jordan-1-black-1");
        group3.add("nike-air-jordan-1-black-2");
        group3.add("nike-air-jordan-1-black-3");
        group3.add("nike-air-jordan-1-black-4");
        group3.add("nike-air-jordan-1-black-5");
        group3.add("nike-air-jordan-1-black-6");
        group4 = new ArrayList<>();
        group4.add("nike-air-jordan-1-white-1");
        group4.add("nike-air-jordan-1-white-2");
        group4.add("nike-air-jordan-1-white-3");
        group4.add("nike-air-jordan-1-white-4");
        group4.add("nike-air-jordan-1-white-5");
        group4.add("nike-air-jordan-1-white-6");
        images.add(group1);
        images.add(group2);
        images.add(group3);
        images.add(group4);
        amazonLinks = sneaker.getAmazonLinks();
        amazonLinks.add("https://www.amazon.com/gp/product/B0093ZC46G/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&tag=sneakeracom-20&camp=1789&creative=9325&linkCode=as2&creativeASIN=B0093ZC46G&linkId=c6a6c787db3f62f534ef06308871e0f0");
        amazonLinks.add("https://www.amazon.com/gp/product/B015R2UWDU/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&tag=sneakeracom-20&camp=1789&creative=9325&linkCode=as2&creativeASIN=B015R2UWDU&linkId=3ec11a0502ebd2024bf3a959dc8497b7");
        amazonLinks.add("https://www.amazon.com/gp/product/B015R2UWDU/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&tag=sneakeracom-20&camp=1789&creative=9325&linkCode=as2&creativeASIN=B015R2UWDU&linkId=3ec11a0502ebd2024bf3a959dc8497b7");
        amazonLinks.add("https://www.amazon.com/gp/product/B015R2UWDU/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&tag=sneakeracom-20&camp=1789&creative=9325&linkCode=as2&creativeASIN=B015R2UWDU&linkId=3ec11a0502ebd2024bf3a959dc8497b7");

        sneaker = urlToSneaker.get("vans-authentic");
        images = sneaker.getImages();
        group1 = new ArrayList<>();
        group1.add("vans-authentic-dark-red-1");
        group1.add("vans-authentic-dark-red-2");
        group1.add("vans-authentic-dark-red-3");
        group1.add("vans-authentic-dark-red-4");
        group1.add("vans-authentic-dark-red-5");
        group1.add("vans-authentic-dark-red-6");
        group1.add("vans-authentic-dark-red-7");
        group2 = new ArrayList<>();
        group2.add("vans-authentic-red-1");
        group2.add("vans-authentic-red-2");
        group2.add("vans-authentic-red-3");
        group2.add("vans-authentic-red-4");
        group2.add("vans-authentic-red-5");
        group2.add("vans-authentic-red-6");
        group2.add("vans-authentic-red-7");
        group2.add("vans-authentic-red-8");
        group3 = new ArrayList<>();
        group3.add("vans-authentic-black-1");
        group3.add("vans-authentic-black-2");
        group3.add("vans-authentic-black-3");
        group3.add("vans-authentic-black-4");
        group3.add("vans-authentic-black-5");
        group3.add("vans-authentic-black-6");
        group3.add("vans-authentic-black-7");
        group3.add("vans-authentic-black-8");
        group3.add("vans-authentic-black-9");
        group3.add("vans-authentic-black-10");
        group4 = new ArrayList<>();
        group4.add("vans-authentic-pink-1");
        group4.add("vans-authentic-pink-2");
        group4.add("vans-authentic-pink-3");
        group4.add("vans-authentic-pink-4");
        images.add(group1);
        images.add(group2);
        images.add(group3);
        images.add(group4);
        amazonLinks = sneaker.getAmazonLinks();
        amazonLinks.add("https://www.amazon.com/gp/product/B00OJD82R2/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&tag=sneakeracom-20&camp=1789&creative=9325&linkCode=as2&creativeASIN=B00OJD82R2&linkId=c606d704b140231e3a81063761d55901");
        amazonLinks.add("https://www.amazon.com/gp/product/B00OJD82R2/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&tag=sneakeracom-20&camp=1789&creative=9325&linkCode=as2&creativeASIN=B00OJD82R2&linkId=c606d704b140231e3a81063761d55901");
        amazonLinks.add("https://www.amazon.com/gp/product/B00OJD82R2/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&tag=sneakeracom-20&camp=1789&creative=9325&linkCode=as2&creativeASIN=B00OJD82R2&linkId=c606d704b140231e3a81063761d55901");
        amazonLinks.add("https://www.amazon.com/gp/product/B00OJD82R2/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&tag=sneakeracom-20&camp=1789&creative=9325&linkCode=as2&creativeASIN=B00OJD82R2&linkId=c606d704b140231e3a81063761d55901");

        sneaker = urlToSneaker.get("new-balance-574");
        images = sneaker.getImages();
        group1 = new ArrayList<>();
        group1.add("new-balance-574-navy-grey-1");
        group1.add("new-balance-574-navy-grey-2");
        group1.add("new-balance-574-navy-grey-3");
        group1.add("new-balance-574-navy-grey-4");
        group1.add("new-balance-574-navy-grey-5");
        group1.add("new-balance-574-navy-grey-6");
        group1.add("new-balance-574-navy-grey-7");
        group2 = new ArrayList<>();
        group2.add("new-balance-574-black-1");
        group2.add("new-balance-574-black-2");
        group2.add("new-balance-574-black-3");
        group2.add("new-balance-574-black-4");
        group2.add("new-balance-574-black-5");
        group2.add("new-balance-574-black-6");
        group2.add("new-balance-574-black-7");
        group3 = new ArrayList<>();
        group3.add("new-balance-574-grey-silver-1");
        group3.add("new-balance-574-grey-silver-2");
        group3.add("new-balance-574-grey-silver-3");
        group3.add("new-balance-574-grey-silver-4");
        group3.add("new-balance-574-grey-silver-5");
        group3.add("new-balance-574-grey-silver-6");
        group4 = new ArrayList<>();
        group4.add("new-balance-574-navy-blue-1");
        group4.add("new-balance-574-navy-blue-2");
        group4.add("new-balance-574-navy-blue-3");
        group4.add("new-balance-574-navy-blue-4");
        group4.add("new-balance-574-navy-blue-5");
        group5 = new ArrayList<>();
        group5.add("new-balance-574-red-1");
        group5.add("new-balance-574-red-2");
        group5.add("new-balance-574-red-3");
        group5.add("new-balance-574-red-4");
        group5.add("new-balance-574-red-5");
        group5.add("new-balance-574-red-6");
        group5.add("new-balance-574-red-7");
        images.add(group5);
        images.add(group1);
        images.add(group2);
        images.add(group3);
        images.add(group4);
        amazonLinks = sneaker.getAmazonLinks();
        amazonLinks.add("https://www.amazon.com/gp/product/B018ND2CA6/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&tag=sneakeracom-20&camp=1789&creative=9325&linkCode=as2&creativeASIN=B018ND2CA6&linkId=94f45a90f5c38ea383f9721a17e5df1f");
        amazonLinks.add("https://www.amazon.com/gp/product/B000HKAMHE/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&tag=sneakeracom-20&camp=1789&creative=9325&linkCode=as2&creativeASIN=B000HKAMHE&linkId=8cf94bb72f837917b863cc938393ba5c");
        amazonLinks.add("https://www.amazon.com/gp/product/B000HKAMHE/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&tag=sneakeracom-20&camp=1789&creative=9325&linkCode=as2&creativeASIN=B000HKAMHE&linkId=8cf94bb72f837917b863cc938393ba5c");
        amazonLinks.add("https://www.amazon.com/gp/product/B000HKAMHE/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&tag=sneakeracom-20&camp=1789&creative=9325&linkCode=as2&creativeASIN=B000HKAMHE&linkId=8cf94bb72f837917b863cc938393ba5c");
        amazonLinks.add("https://www.amazon.com/gp/product/B000HKAMHE/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&tag=sneakeracom-20&camp=1789&creative=9325&linkCode=as2&creativeASIN=B000HKAMHE&linkId=8cf94bb72f837917b863cc938393ba5c");

        sneaker = urlToSneaker.get("adidas-stan-smith");
        images = sneaker.getImages();
        group1 = new ArrayList<>();
        group1.add("adidas-stan-smith-white-green-1");
        group1.add("adidas-stan-smith-white-green-2");
        group1.add("adidas-stan-smith-white-green-3");
        group1.add("adidas-stan-smith-white-green-4");
        group1.add("adidas-stan-smith-white-green-5");
        group1.add("adidas-stan-smith-white-green-6");
        group1.add("adidas-stan-smith-white-green-7");
        group1.add("adidas-stan-smith-white-green-8");
        group2 = new ArrayList<>();
        group2.add("adidas-stan-smith-white-red-1");
        group2.add("adidas-stan-smith-white-red-2");
        group2.add("adidas-stan-smith-white-red-3");
        group2.add("adidas-stan-smith-white-red-4");
        group2.add("adidas-stan-smith-white-red-5");
        group2.add("adidas-stan-smith-white-red-6");
        group2.add("adidas-stan-smith-white-red-7");
        group3 = new ArrayList<>();
        group3.add("adidas-stan-smith-white-black-1");
        group3.add("adidas-stan-smith-white-black-2");
        group3.add("adidas-stan-smith-white-black-3");
        group3.add("adidas-stan-smith-white-black-4");
        group3.add("adidas-stan-smith-white-black-5");
        group3.add("adidas-stan-smith-white-black-6");
        group3.add("adidas-stan-smith-white-black-7");
        group4 = new ArrayList<>();
        group4.add("adidas-stan-smith-red-1");
        group4.add("adidas-stan-smith-red-2");
        group4.add("adidas-stan-smith-red-3");
        group4.add("adidas-stan-smith-red-4");
        group4.add("adidas-stan-smith-red-5");
        group4.add("adidas-stan-smith-red-6");
        group4.add("adidas-stan-smith-red-7");
        group5 = new ArrayList<>();
        group5.add("adidas-stan-smith-black-1");
        group5.add("adidas-stan-smith-black-2");
        group5.add("adidas-stan-smith-black-3");
        group5.add("adidas-stan-smith-black-4");
        group5.add("adidas-stan-smith-black-5");
        group5.add("adidas-stan-smith-black-6");
        group5.add("adidas-stan-smith-black-7");
        group5.add("adidas-stan-smith-black-8");
        images.add(group1);
        images.add(group2);
        images.add(group3);
        images.add(group4);
        images.add(group5);
        amazonLinks = sneaker.getAmazonLinks();
        amazonLinks.add("https://www.amazon.com/gp/product/B00J5IKX14/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&tag=sneakeracom-20&camp=1789&creative=9325&linkCode=as2&creativeASIN=B00J5IKX14&linkId=db1a29d0f3274e169d8f1574971c0d1c");
        amazonLinks.add("https://www.amazon.com/gp/product/B00J5IKX14/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&tag=sneakeracom-20&camp=1789&creative=9325&linkCode=as2&creativeASIN=B00J5IKX14&linkId=db1a29d0f3274e169d8f1574971c0d1c");
        amazonLinks.add("https://www.amazon.com/gp/product/B00J5IKX14/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&tag=sneakeracom-20&camp=1789&creative=9325&linkCode=as2&creativeASIN=B00J5IKX14&linkId=db1a29d0f3274e169d8f1574971c0d1c");
        amazonLinks.add("https://www.amazon.com/gp/product/B00J5IKX14/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&tag=sneakeracom-20&camp=1789&creative=9325&linkCode=as2&creativeASIN=B00J5IKX14&linkId=db1a29d0f3274e169d8f1574971c0d1c");
        amazonLinks.add("https://www.amazon.com/gp/product/B00J5IKX14/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&tag=sneakeracom-20&camp=1789&creative=9325&linkCode=as2&creativeASIN=B00J5IKX14&linkId=db1a29d0f3274e169d8f1574971c0d1c");

        sneaker = urlToSneaker.get("puma-suede");
        images = sneaker.getImages();
        group1 = new ArrayList<>();
        group1.add("puma-suede-dark-green-dark-blue-1");
        group1.add("puma-suede-dark-green-dark-blue-2");
        group1.add("puma-suede-dark-green-dark-blue-3");
        group1.add("puma-suede-dark-green-dark-blue-4");
        group1.add("puma-suede-dark-green-dark-blue-5");
        group1.add("puma-suede-dark-green-dark-blue-6");
        group1.add("puma-suede-dark-green-dark-blue-7");
        group2 = new ArrayList<>();
        group2.add("puma-suede-red-white-1");
        group2.add("puma-suede-red-white-2");
        group2.add("puma-suede-red-white-3");
        group2.add("puma-suede-red-white-4");
        group2.add("puma-suede-red-white-5");
        group2.add("puma-suede-red-white-6");
        group2.add("puma-suede-red-white-7");
        group3 = new ArrayList<>();
        group3.add("puma-suede-blue-orange-1");
        group3.add("puma-suede-blue-orange-2");
        group3.add("puma-suede-blue-orange-3");
        group3.add("puma-suede-blue-orange-4");
        group3.add("puma-suede-blue-orange-5");
        group3.add("puma-suede-blue-orange-6");
        group3.add("puma-suede-blue-orange-7");
        group4 = new ArrayList<>();
        group4.add("puma-suede-orange-blue-1");
        group4.add("puma-suede-orange-blue-2");
        group4.add("puma-suede-orange-blue-3");
        group4.add("puma-suede-orange-blue-4");
        group4.add("puma-suede-orange-blue-5");
        group4.add("puma-suede-orange-blue-6");
        group4.add("puma-suede-orange-blue-7");
        group5 = new ArrayList<>();
        group5.add("puma-suede-brown-black-1");
        group5.add("puma-suede-brown-black-2");
        group5.add("puma-suede-brown-black-3");
        group5.add("puma-suede-brown-black-4");
        group5.add("puma-suede-brown-black-5");
        group5.add("puma-suede-brown-black-6");
        group6 = new ArrayList<>();
        group6.add("puma-suede-red-dark-blue-1");
        group6.add("puma-suede-red-dark-blue-2");
        group6.add("puma-suede-red-dark-blue-3");
        group6.add("puma-suede-red-dark-blue-4");
        group6.add("puma-suede-red-dark-blue-5");
        group6.add("puma-suede-red-dark-blue-6");
        group6.add("puma-suede-red-dark-blue-7");
        group7 = new ArrayList<>();
        group7.add("puma-suede-black-white-1");
        group7.add("puma-suede-black-white-2");
        group7.add("puma-suede-black-white-3");
        group7.add("puma-suede-black-white-4");
        group7.add("puma-suede-black-white-5");
        group7.add("puma-suede-black-white-6");
        group7 = new ArrayList<>();
        group7.add("puma-suede-green-1");
        group7.add("puma-suede-green-2");
        group7.add("puma-suede-green-3");
        group7.add("puma-suede-green-4");
        group7.add("puma-suede-green-5");
        group7.add("puma-suede-green-6");
        group7.add("puma-suede-green-7");
        images.add(group1);
        images.add(group2);
        images.add(group3);
        images.add(group4);
        images.add(group5);
        images.add(group6);
        images.add(group7);
        amazonLinks = sneaker.getAmazonLinks();
        amazonLinks.add("https://www.amazon.com/gp/product/B0058XFMYS/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&tag=sneakeracom-20&camp=1789&creative=9325&linkCode=as2&creativeASIN=B0058XFMYS&linkId=7bdca3dfab8de7a22eeeb58c119e1e0a");
        amazonLinks.add("https://www.amazon.com/gp/product/B0058XFMYS/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&tag=sneakeracom-20&camp=1789&creative=9325&linkCode=as2&creativeASIN=B0058XFMYS&linkId=7bdca3dfab8de7a22eeeb58c119e1e0a");
        amazonLinks.add("https://www.amazon.com/gp/product/B0058XFMYS/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&tag=sneakeracom-20&camp=1789&creative=9325&linkCode=as2&creativeASIN=B0058XFMYS&linkId=7bdca3dfab8de7a22eeeb58c119e1e0a");
        amazonLinks.add("https://www.amazon.com/gp/product/B0058XFMYS/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&tag=sneakeracom-20&camp=1789&creative=9325&linkCode=as2&creativeASIN=B0058XFMYS&linkId=7bdca3dfab8de7a22eeeb58c119e1e0a");
        amazonLinks.add("https://www.amazon.com/gp/product/B0058XFMYS/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&tag=sneakeracom-20&camp=1789&creative=9325&linkCode=as2&creativeASIN=B0058XFMYS&linkId=7bdca3dfab8de7a22eeeb58c119e1e0a");
        amazonLinks.add("https://www.amazon.com/gp/product/B0058XFMYS/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&tag=sneakeracom-20&camp=1789&creative=9325&linkCode=as2&creativeASIN=B0058XFMYS&linkId=7bdca3dfab8de7a22eeeb58c119e1e0a");
        amazonLinks.add("https://www.amazon.com/gp/product/B0058XFMYS/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&tag=sneakeracom-20&camp=1789&creative=9325&linkCode=as2&creativeASIN=B0058XFMYS&linkId=7bdca3dfab8de7a22eeeb58c119e1e0a");

        LOGGER.info("Finished populating image data.");
    }
}
